//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarNegotiator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BidVM
    {

        public int id { get; set; }
        public string DealerName { get; set; }
        public string MobileNumber { get; set; }
        public string TelephoneNumber { get; set; }
        public string emailAddress { get; set; }
        public string businessName { get; set; }
        public string Province { get; set; }
        public string Town { get; set; }
        public Nullable<int> bidAmount { get; set; }
        public string dealerComments { get; set; }
        public Nullable<System.DateTime> bidUpdatedDate { get; set; }
        public bool? winningBid { get; set; }
    }
}
