//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarNegotiator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarRequestVM
    {
        public int id { get; set; }
        public string ClientName { get; set; }
        public string car { get; set; }
        public int carVariantId { get; set; }
        public System.DateTime requestedDate { get; set; }
        public System.DateTime BidClosingDate { get; set; }
        public System.DateTime deliveryRequestDate { get; set; }
        public string clientComments { get; set; }
        public string AdminComments { get; set; }
        public bool isRequestClosed { get; set; }
        public bool isRequestActive { get; set; }
    }
}