//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarNegotiator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestsBidsVM
    {
        public int requestId { get; set; }
        public int dealerId { get; set; }
        public int? bidId { get; set; }
        public string car { get; set; }
        public int carMakeId { get; set; }
        public int carVariantId { get; set; }
        public string Colors { get; set; }
        public bool isFinanceApproved { get; set; }
        public int provinceId { get; set; }
        public string Province { get; set; }
        public string Town { get; set; }
        public System.DateTime requestedDate { get; set; }
        public System.DateTime BidClosingDate { get; set; }
        public int? WinningBid { get; set; }
        public int? YourBid { get; set; }
        public bool? isDealerInterested { get; set; }
    }
}
