//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarNegotiator.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public class ClientMetaData
    {



        [Display(Name = "Please select Title")]
        [UIHint("Dropdown")]
        public Nullable<int> titleId { get; set; }

        [Display(Name = "First Name (Required)",Prompt = "Please enter first name")]
        [Required(ErrorMessage = "First Name is required ")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "First Name should be between 2 to 50 Characters")]
        [UIHint("RequiredTextbox")]
        public string firstName { get; set; }

        [Display(Name = "Last Name (Optional)")]
        public string lastName { get; set; }

        [Display(Name = "Contact Number (Required)")]
        [Required(ErrorMessage = "Contact Number is required")]
        [DataType(DataType.PhoneNumber)]
        [StringLength(15, MinimumLength = 10, ErrorMessage = "Contact Number should be between 10 to 15 Characters")]
        public string contactNumber { get; set; }

        [Display(Name = "Best Time to Contact you")]
        [Required(ErrorMessage = "Please select the {0}")]
        public int bestTimeToContactId { get; set; }

        [Display(Name = "Email Address (Required)", Prompt = "Please enter email address.This is your login Id")]
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "Email address is required")]
        [UIHint("RequiredTextbox")]
        public string emailAddress { get; set; }

        [Display(Name = "Password (Required)",Prompt = "Please enter password")]
        [Required(ErrorMessage = "Password is required")]
        [DataType(DataType.Password)]
        [UIHint("PassWordTextBox")]
        [StringLength(15, MinimumLength = 8, ErrorMessage = "Password must be between 8 to 15 Characters")]
        public string password { get; set; }

        [Display(Name = "Remember Me")]
        [ScaffoldColumn(false)]
        public Nullable<bool> rememberMe { get; set; }

        [Display(Name = "Please select your province")]
        [Required(ErrorMessage = "Province is required")]
        public int provinceId { get; set; }

        [Display(Name = "Please select Town")]
        [Required(ErrorMessage = "Town is required")]
        public int townId { get; set; }

        [Display(Name = "Notify by email for new bids")]
        public bool bidemailnotify { get; set; }

        [Display(Name = "Notify by SMS for new bids")]
        public bool bidsmsnotify { get; set; }

        [Display(Name = "Notify by email for a day before bid is closing")]
        public bool closenextdayemailnotify { get; set; }

        [Display(Name = "Notify by SMS for a day before bid is closing")]
        public bool closenextdaysmsnotify { get; set; }

        [Display(Name = "Notify by email when a bid is closed")]
        public bool closedemailnotify { get; set; }

        [Display(Name = "Notify by SMS when a bid is closed")]
        public bool closedsmsnotify { get; set; }

        [ScaffoldColumn(false)]
        public Nullable<bool> isEmailConfirmed { get; set; }
        [ScaffoldColumn(false)]
        public System.DateTime createdDate { get; set; }
        [ScaffoldColumn(false)]
        public Nullable<System.DateTime> modifiedDate { get; set; }
        [ScaffoldColumn(false)]
        public Nullable<System.DateTime> lastLoginDate { get; set; }

    }

    [MetadataType(typeof(ClientMetaData))]
    public partial class Client
    {
        public IEnumerable<SelectListItem> Titles;
       
    }
}
