//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarNegotiator.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public class UsersMetaData
    {

        [Display(Name = "Please select Title")]
        public Nullable<int> titleId { get; set; }

        [Display(Name = "First Name (Required)", Prompt = "Please enter first name")]
        [Required(ErrorMessage = "First Name is required ")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "First Name should be between 2 to 50 Characters")]
        [UIHint("RequiredTextbox")]
        public string firstName { get; set; }

        [Display(Name = "Last Name (Optional)",  Prompt = "Please enter Last Name")]
        [UIHint("OptionalTextbox")]
        public string lastName { get; set; }

        [Display(Name = "Contact Number Number (Required)", Prompt = "Please enter Last Name")]
        [UIHint("RequiredTextbox")]
        [Required(ErrorMessage = "Contact Number is required")]
        [StringLength(15, MinimumLength = 10, ErrorMessage = "Contact Number should be between 10 to 15 Characters")]
        [DataType(DataType.PhoneNumber)]
        public string contactNumber { get; set; }

        [Display(Name = "Email Address (Required)", Prompt = "Please enter email address.This is your login Id")]
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "Email address is required")]
        [UIHint("RequiredTextbox")]
        public string emailAddress { get; set; }


        [Display(Name = "Password (Required)", Prompt = "Please enter password")]
        [Required(ErrorMessage = "Password is required")]
        [DataType(DataType.Password)]
        [UIHint("PassWordTextBox")]
        public string password { get; set; }

        [Display(Name = "Please select your province")]
        [Required(ErrorMessage = "Province is required")]
        public int provinceId { get; set; }

        [Display(Name = "Please select Town")]
        [Required(ErrorMessage = "Town is required")]
        public int townId { get; set; }

    }

    [MetadataType(typeof(UsersMetaData))]
    public partial class User
    {
      
       
    }
}
