//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarNegotiator.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutoNegotiatorDBEntities : DbContext
    {
        public AutoNegotiatorDBEntities()
            : base("name=AutoNegotiatorDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BestTimeToContact> BestTimeToContacts { get; set; }
        public virtual DbSet<Bid> Bids { get; set; }
        public virtual DbSet<CarMake> CarMakes { get; set; }
        public virtual DbSet<CarModel> CarModels { get; set; }
        public virtual DbSet<CarRequest> CarRequests { get; set; }
        public virtual DbSet<CarVariantFuel> CarVariantFuels { get; set; }
        public virtual DbSet<CarVariant> CarVariants { get; set; }
        public virtual DbSet<CarVariantYear> CarVariantYears { get; set; }
        public virtual DbSet<ClientLogin> ClientLogins { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<DealerLogin> DealerLogins { get; set; }
        public virtual DbSet<DealerMake> DealerMakes { get; set; }
        public virtual DbSet<DealerProvince> DealerProvinces { get; set; }
        public virtual DbSet<Dealer> Dealers { get; set; }
        public virtual DbSet<Faq_Types> Faq_Types { get; set; }
        public virtual DbSet<Faq> Faqs { get; set; }
        public virtual DbSet<FinanceHous> FinanceHouses { get; set; }
        public virtual DbSet<PaymentGateway> PaymentGateways { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<Town> Towns { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
    }
}
