//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarNegotiator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarRequest()
        {
            this.Bids = new HashSet<Bid>();
        }
    
        public int id { get; set; }
        public int carVariantId { get; set; }
        public int clientId { get; set; }
        public System.DateTime requestedDate { get; set; }
        public System.DateTime deliveryRequestDate { get; set; }
        public Nullable<int> colorChoice1Id { get; set; }
        public Nullable<int> colorChoice2Id { get; set; }
        public Nullable<int> colorChoice3Id { get; set; }
        public bool canOfferDifferentColor { get; set; }
        public Nullable<int> paymentMethodId { get; set; }
        public bool financeApproved { get; set; }
        public Nullable<int> financeHouseId { get; set; }
        public Nullable<int> depositAmount { get; set; }
        public bool tradeinVehicleAvailable { get; set; }
        public Nullable<int> tradeinMakeId { get; set; }
        public Nullable<int> tradeinModelId { get; set; }
        public Nullable<int> tradeinVariantId { get; set; }
        public Nullable<int> tradeinYearId { get; set; }
        public Nullable<int> tradeinFuelId { get; set; }
        public string tradeinDescription { get; set; }
        public Nullable<int> tradeinValue { get; set; }
        public Nullable<int> tradeinKMs { get; set; }
        public string clientComments { get; set; }
        public bool isRequestActive { get; set; }
        public Nullable<int> winningBidId { get; set; }
        public Nullable<bool> clientAcceptedWinningBid { get; set; }
        public Nullable<int> actualSellingPrice { get; set; }
        public Nullable<int> commissionCalculated { get; set; }
        public Nullable<int> commisionReceived { get; set; }
        public string AdminComments { get; set; }
        public bool isRequestClosed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bid> Bids { get; set; }
        public virtual Bid Bid { get; set; }
        public virtual CarMake CarMake { get; set; }
        public virtual CarModel CarModel { get; set; }
        public virtual Client Client { get; set; }
        public virtual CarVariant CarVariant { get; set; }
        public virtual CarVariantFuel CarVariantFuel { get; set; }
        public virtual CarVariant CarVariant1 { get; set; }
        public virtual CarVariantYear CarVariantYear { get; set; }
        public virtual Color Color { get; set; }
        public virtual Color Color1 { get; set; }
        public virtual Color Color2 { get; set; }
        public virtual FinanceHous FinanceHous { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
    }
}
