//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarNegotiator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarVariant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarVariant()
        {
            this.CarRequests = new HashSet<CarRequest>();
            this.CarRequests1 = new HashSet<CarRequest>();
        }
    
        public int id { get; set; }
        public int carModelId { get; set; }
        public string carVariantName { get; set; }
        public bool isActive { get; set; }
        public Nullable<int> AveragePrice { get; set; }
        public string BodyType { get; set; }
        public string Cylinder_layout_quantity { get; set; }
        public string Drive { get; set; }
        public string Engine_capacity { get; set; }
        public string Engine_detail { get; set; }
        public string Engine_size_litre { get; set; }
        public string Fuel_tank_capacity_incl_reserve { get; set; }
        public string Fuel_type { get; set; }
        public string Gears { get; set; }
        public string Gearshift_paddles { get; set; }
        public string Low_range { get; set; }
        public string No_of_doors { get; set; }
        public string Sunroof { get; set; }
        public string Gearbox { get; set; }
        public string Transmission_name { get; set; }
        public string Turbocharger { get; set; }
        public string Air_conditioning { get; set; }
        public string Aux_in_auxiliary_input_jack { get; set; }
        public string Bluetooth_connectivity { get; set; }
        public string Camera_for_park_distance_control { get; set; }
        public string Climate_control__automatic_air_conditioning { get; set; }
        public string Cruise_control { get; set; }
        public string Electric_steering_column_adjustment { get; set; }
        public string Electric_adjust_mirrors { get; set; }
        public string Engine_auto_StopStart__idle_stop__eco_stop { get; set; }
        public string Maintenance_plan { get; set; }
        public string Maintenance_plan_distance { get; set; }
        public string Maintenance_plan_time_years { get; set; }
        public string Multi_function_steering_wheel_controls { get; set; }
        public string Navigation { get; set; }
        public string Park_distance_control_PDC___front { get; set; }
        public string Park_distance_control_PDC___rear { get; set; }
        public string Power_steering { get; set; }
        public string Service_interval_distance { get; set; }
        public string USB_port { get; set; }
        public string Voice_control { get; set; }
        public string Warranty_distance { get; set; }
        public string Warranty_time_years { get; set; }
        public string Acceleration_0100km_h { get; set; }
        public string Co2_emissions { get; set; }
        public string Engine_position_location { get; set; }
        public string Fuel_range_average { get; set; }
        public string Fuel_consumption_average { get; set; }
        public string Maximum_top_speed { get; set; }
        public string Power_maximum_detail { get; set; }
        public string Power_peak_revs { get; set; }
        public string Torque_maximum { get; set; }
        public string Torque_peak_revs { get; set; }
        public string CD_player { get; set; }
        public string Electric_seat_adjustment_driver { get; set; }
        public string Electric_seat_adjustment_front_passenger { get; set; }
        public string Electric_windows { get; set; }
        public string Folding_rear_seat { get; set; }
        public string Heated_seats___front { get; set; }
        public string ISOFIX_child_seat_mountings { get; set; }
        public string Leather_upholstery { get; set; }
        public string On_board_computer__multi_information_display { get; set; }
        public string Seats { get; set; }
        public string Split_rear_seat { get; set; }
        public string Ventilated_seats___front { get; set; }
        public string Airbag_quantity { get; set; }
        public string Anti_lock_braking_system_ABS { get; set; }
        public string Autodim_exterior_mirrors { get; set; }
        public string Autodim_interior_mirror { get; set; }
        public string Brake_assist_BASEBA { get; set; }
        public string Curtain_airbags { get; set; }
        public string Daytime_drivingrunning_lights { get; set; }
        public string Diff_lock___centre { get; set; }
        public string Diff_lock___front { get; set; }
        public string Diff_lock___rear { get; set; }
        public string Driver_airbag { get; set; }
        public string Electronic_brake_distribution_EBD { get; set; }
        public string Emergency_brake_hazard_lights { get; set; }
        public string Front_fog_lampslights { get; set; }
        public string Front_passenger_airbag { get; set; }
        public string High_level_3rd_brake_light { get; set; }
        public string Hill_start_assist__hill_holder { get; set; }
        public string Lane_change__blind_spot_warningassistmonitor { get; set; }
        public string Light_sensor__automatic_light_control_auto_on_off_lights { get; set; }
        public string Rain_sensor_auto_wipers { get; set; }
        public string Remote_central_locking { get; set; }
        public string Stability_control { get; set; }
        public string Traction_control { get; set; }
        public string Tyre_pressure_sensormonitor__deflation_detection_system { get; set; }
        public string Xenon_headlights { get; set; }
        public string Alloy_wheelsrims { get; set; }
        public string Approach_angle { get; set; }
        public string Axle_configuration { get; set; }
        public string Breakover_ramp_angle { get; set; }
        public string Departure_angle { get; set; }
        public string Front_tyres { get; set; }
        public string Gross_weight_GVM { get; set; }
        public string Ground_clearance_minimummaximum { get; set; }
        public string Height { get; set; }
        public string Length { get; set; }
        public string Rear_tyres { get; set; }
        public string Wheelbase { get; set; }
        public string Width_excl_mirrors_incl_mirrors { get; set; }
    
        public virtual CarModel CarModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarRequest> CarRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarRequest> CarRequests1 { get; set; }
    }
}
