//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarNegotiator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.CarRequests = new HashSet<CarRequest>();
            this.ClientLogins = new HashSet<ClientLogin>();
        }
    
        public int id { get; set; }
        public Nullable<int> titleId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string contactNumber { get; set; }
        public int bestTimeToContactId { get; set; }
        public string emailAddress { get; set; }
        public string password { get; set; }
        public Nullable<bool> rememberMe { get; set; }
        public Nullable<bool> isEmailConfirmed { get; set; }
        public int provinceId { get; set; }
        public int townId { get; set; }
        public System.DateTime createdDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public Nullable<System.DateTime> lastLoginDate { get; set; }
        public bool bidemailnotify { get; set; }
        public bool bidsmsnotify { get; set; }
        public bool closenextdayemailnotify { get; set; }
        public bool closenextdaysmsnotify { get; set; }
        public bool closedemailnotify { get; set; }
        public bool closedsmsnotify { get; set; }
    
        public virtual BestTimeToContact BestTimeToContact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarRequest> CarRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientLogin> ClientLogins { get; set; }
        public virtual Town Town { get; set; }
        public virtual Province Province { get; set; }
        public virtual Title Title { get; set; }
    }
}
