//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarNegotiator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealerLogin
    {
        public int Id { get; set; }
        public int dealerId { get; set; }
        public System.DateTime logintime { get; set; }
        public Nullable<System.DateTime> logouttime { get; set; }
    
        public virtual Dealer Dealer { get; set; }
    }
}
