//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarNegotiator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dealer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dealer()
        {
            this.Bids = new HashSet<Bid>();
            this.DealerLogins = new HashSet<DealerLogin>();
            this.DealerMakes = new HashSet<DealerMake>();
            this.DealerProvinces = new HashSet<DealerProvince>();
        }
    
        public int id { get; set; }
        public int titleId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string MobileNumber { get; set; }
        public string TelephoneNumber { get; set; }
        public string emailAddress { get; set; }
        public string password { get; set; }
        public bool rememberMe { get; set; }
        public bool isEmailConfirmed { get; set; }
        public int provinceId { get; set; }
        public int townId { get; set; }
        public System.DateTime createdDate { get; set; }
        public System.DateTime modifiedDate { get; set; }
        public Nullable<System.DateTime> lastLoginDate { get; set; }
        public bool isActive { get; set; }
        public string Position { get; set; }
        public string businessName { get; set; }
        public string registrationNumber { get; set; }
        public string VATNumber { get; set; }
        public string Address { get; set; }
        public int paymentGatewayId { get; set; }
        public bool newlistemailnotify { get; set; }
        public bool newlistsmsnotify { get; set; }
        public bool lowerbidemailnotify { get; set; }
        public bool lowerbidsmsnotify { get; set; }
        public bool closenextdayemailnotify { get; set; }
        public bool closenextdaysmsnotify { get; set; }
        public bool closedemailnotify { get; set; }
        public bool closedsmsnotify { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bid> Bids { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealerLogin> DealerLogins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealerMake> DealerMakes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealerProvince> DealerProvinces { get; set; }
        public virtual Town Town { get; set; }
        public virtual PaymentGateway PaymentGateway { get; set; }
        public virtual Province Province { get; set; }
        public virtual Title Title { get; set; }
    }
}
