//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarNegotiator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealerMake
    {
        public int Id { get; set; }
        public int dealerId { get; set; }
        public int carMakeId { get; set; }
        public bool isActive { get; set; }
    
        public virtual CarMake CarMake { get; set; }
        public virtual Dealer Dealer { get; set; }
    }
}
