//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarNegotiator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faq
    {
        public int id { get; set; }
        public int faqtypeId { get; set; }
        public string question { get; set; }
        public string answer { get; set; }
    
        public virtual Faq_Types Faq_Types { get; set; }
    }
}
